Algoritmo "Dobro"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Aryon Rabello Jeronymo
// Data atual  : 11/06/2021
Var
// Seção de Declarações das variáveis 
   v1:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um valor: ")
   leia(v1)
   escreval("")
   escreval("O dobro do valor é:", v1 * 2)

Fimalgoritmo