Algoritmo "1-CONTAR_0a10"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Aryon Rabello Jeronymo
// Data atual  : 13/07/2021
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   enquanto num <= 10 faca
            escreval(num)
            num <- num + 1
   fimenquanto

Fimalgoritmo