Algoritmo "2 - CONTAR_0a20"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Aryon Rabello Jeronymo
// Data atual  : 13/07/2021
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto num <= 20 faca
         escreval(num)
         num <- num + 2
fimenquanto

Fimalgoritmo