Algoritmo "3 - CONTAR_0a30"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Aryon Rabello Jeronymo
// Data atual  : 13/07/2021
Var
// Seção de Declarações das variáveis 
numI, numF: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite o número máximo da contagem: ")
leia(numF)
 
enquanto numI <= numF faca
         escreval(numI)
         numI <- numI + 1
fimenquanto

Fimalgoritmo