Algoritmo "2 - CONTAR_10a0"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Aryon Rabello Jeronymo
// Data atual  : 13/07/2021
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
num <- 10
 
enquanto num >= 0 faca
         escreval(num)
         num <- num -1
fimenquanto

Fimalgoritmo